/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabCasesRouteImport } from './routes/lab/cases'
import { Route as LabClaimsRouteImport } from './routes/lab/claims'
import { Route as LabEvidenceRouteImport } from './routes/lab/evidence'
import { Route as LabExperimentsRouteImport } from './routes/lab/experiments'
import { Route as LabGenomeRouteImport } from './routes/lab/genome'
import { Route as LabGovernanceRouteImport } from './routes/lab/governance'
import { Route as LabLoopsRouteImport } from './routes/lab/loops'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LabCasesCaseIdRouteImport } from './routes/lab/cases.$caseId'
import { Route as LabGenomeOperatorIdRouteImport } from './routes/lab/genome.$operatorId'
import { Route as LabLoopsLoopIdRouteImport } from './routes/lab/loops.$loopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const LabCasesRoute = LabCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LabRoute,
} as any)
const LabClaimsRoute = LabClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => LabRoute,
} as any)
const LabEvidenceRoute = LabEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => LabRoute,
} as any)
const LabExperimentsRoute = LabExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => LabRoute,
} as any)
const LabGenomeRoute = LabGenomeRouteImport.update({
  id: '/genome',
  path: '/genome',
  getParentRoute: () => LabRoute,
} as any)
const LabGovernanceRoute = LabGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => LabRoute,
} as any)
const LabLoopsRoute = LabLoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => LabRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCasesCaseIdRoute = LabCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => LabCasesRoute,
} as any)
const LabGenomeOperatorIdRoute = LabGenomeOperatorIdRouteImport.update({
  id: '/$operatorId',
  path: '/$operatorId',
  getParentRoute: () => LabGenomeRoute,
} as any)
const LabLoopsLoopIdRoute = LabLoopsLoopIdRouteImport.update({
  id: '/$loopId',
  path: '/$loopId',
  getParentRoute: () => LabLoopsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/lab/cases': typeof LabCasesRouteWithChildren
  '/lab/claims': typeof LabClaimsRoute
  '/lab/evidence': typeof LabEvidenceRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/genome': typeof LabGenomeRouteWithChildren
  '/lab/governance': typeof LabGovernanceRoute
  '/lab/loops': typeof LabLoopsRouteWithChildren
  '/lab/': typeof LabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lab/cases/$caseId': typeof LabCasesCaseIdRoute
  '/lab/genome/$operatorId': typeof LabGenomeOperatorIdRoute
  '/lab/loops/$loopId': typeof LabLoopsLoopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lab/cases': typeof LabCasesRouteWithChildren
  '/lab/claims': typeof LabClaimsRoute
  '/lab/evidence': typeof LabEvidenceRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/genome': typeof LabGenomeRouteWithChildren
  '/lab/governance': typeof LabGovernanceRoute
  '/lab/loops': typeof LabLoopsRouteWithChildren
  '/lab': typeof LabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lab/cases/$caseId': typeof LabCasesCaseIdRoute
  '/lab/genome/$operatorId': typeof LabGenomeOperatorIdRoute
  '/lab/loops/$loopId': typeof LabLoopsLoopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/lab/cases': typeof LabCasesRouteWithChildren
  '/lab/claims': typeof LabClaimsRoute
  '/lab/evidence': typeof LabEvidenceRoute
  '/lab/experiments': typeof LabExperimentsRoute
  '/lab/genome': typeof LabGenomeRouteWithChildren
  '/lab/governance': typeof LabGovernanceRoute
  '/lab/loops': typeof LabLoopsRouteWithChildren
  '/lab/': typeof LabIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lab/cases/$caseId': typeof LabCasesCaseIdRoute
  '/lab/genome/$operatorId': typeof LabGenomeOperatorIdRoute
  '/lab/loops/$loopId': typeof LabLoopsLoopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/login'
    | '/lab/cases'
    | '/lab/claims'
    | '/lab/evidence'
    | '/lab/experiments'
    | '/lab/genome'
    | '/lab/governance'
    | '/lab/loops'
    | '/lab/'
    | '/api/auth/$'
    | '/lab/cases/$caseId'
    | '/lab/genome/$operatorId'
    | '/lab/loops/$loopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lab/cases'
    | '/lab/claims'
    | '/lab/evidence'
    | '/lab/experiments'
    | '/lab/genome'
    | '/lab/governance'
    | '/lab/loops'
    | '/lab'
    | '/api/auth/$'
    | '/lab/cases/$caseId'
    | '/lab/genome/$operatorId'
    | '/lab/loops/$loopId'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/login'
    | '/lab/cases'
    | '/lab/claims'
    | '/lab/evidence'
    | '/lab/experiments'
    | '/lab/genome'
    | '/lab/governance'
    | '/lab/loops'
    | '/lab/'
    | '/api/auth/$'
    | '/lab/cases/$caseId'
    | '/lab/genome/$operatorId'
    | '/lab/loops/$loopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/cases': {
      id: '/lab/cases'
      path: '/cases'
      fullPath: '/lab/cases'
      preLoaderRoute: typeof LabCasesRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/claims': {
      id: '/lab/claims'
      path: '/claims'
      fullPath: '/lab/claims'
      preLoaderRoute: typeof LabClaimsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/evidence': {
      id: '/lab/evidence'
      path: '/evidence'
      fullPath: '/lab/evidence'
      preLoaderRoute: typeof LabEvidenceRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/experiments': {
      id: '/lab/experiments'
      path: '/experiments'
      fullPath: '/lab/experiments'
      preLoaderRoute: typeof LabExperimentsRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/genome': {
      id: '/lab/genome'
      path: '/genome'
      fullPath: '/lab/genome'
      preLoaderRoute: typeof LabGenomeRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/governance': {
      id: '/lab/governance'
      path: '/governance'
      fullPath: '/lab/governance'
      preLoaderRoute: typeof LabGovernanceRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/loops': {
      id: '/lab/loops'
      path: '/loops'
      fullPath: '/lab/loops'
      preLoaderRoute: typeof LabLoopsRouteImport
      parentRoute: typeof LabRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/cases/$caseId': {
      id: '/lab/cases/$caseId'
      path: '/$caseId'
      fullPath: '/lab/cases/$caseId'
      preLoaderRoute: typeof LabCasesCaseIdRouteImport
      parentRoute: typeof LabCasesRoute
    }
    '/lab/genome/$operatorId': {
      id: '/lab/genome/$operatorId'
      path: '/$operatorId'
      fullPath: '/lab/genome/$operatorId'
      preLoaderRoute: typeof LabGenomeOperatorIdRouteImport
      parentRoute: typeof LabGenomeRoute
    }
    '/lab/loops/$loopId': {
      id: '/lab/loops/$loopId'
      path: '/$loopId'
      fullPath: '/lab/loops/$loopId'
      preLoaderRoute: typeof LabLoopsLoopIdRouteImport
      parentRoute: typeof LabLoopsRoute
    }
  }
}

interface LabCasesRouteChildren {
  LabCasesCaseIdRoute: typeof LabCasesCaseIdRoute
}

const LabCasesRouteChildren: LabCasesRouteChildren = {
  LabCasesCaseIdRoute: LabCasesCaseIdRoute,
}

const LabCasesRouteWithChildren = LabCasesRoute._addFileChildren(
  LabCasesRouteChildren,
)

interface LabGenomeRouteChildren {
  LabGenomeOperatorIdRoute: typeof LabGenomeOperatorIdRoute
}

const LabGenomeRouteChildren: LabGenomeRouteChildren = {
  LabGenomeOperatorIdRoute: LabGenomeOperatorIdRoute,
}

const LabGenomeRouteWithChildren = LabGenomeRoute._addFileChildren(
  LabGenomeRouteChildren,
)

interface LabLoopsRouteChildren {
  LabLoopsLoopIdRoute: typeof LabLoopsLoopIdRoute
}

const LabLoopsRouteChildren: LabLoopsRouteChildren = {
  LabLoopsLoopIdRoute: LabLoopsLoopIdRoute,
}

const LabLoopsRouteWithChildren = LabLoopsRoute._addFileChildren(
  LabLoopsRouteChildren,
)

interface LabRouteChildren {
  LabCasesRoute: typeof LabCasesRouteWithChildren
  LabClaimsRoute: typeof LabClaimsRoute
  LabEvidenceRoute: typeof LabEvidenceRoute
  LabExperimentsRoute: typeof LabExperimentsRoute
  LabGenomeRoute: typeof LabGenomeRouteWithChildren
  LabGovernanceRoute: typeof LabGovernanceRoute
  LabLoopsRoute: typeof LabLoopsRouteWithChildren
  LabIndexRoute: typeof LabIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabCasesRoute: LabCasesRouteWithChildren,
  LabClaimsRoute: LabClaimsRoute,
  LabEvidenceRoute: LabEvidenceRoute,
  LabExperimentsRoute: LabExperimentsRoute,
  LabGenomeRoute: LabGenomeRouteWithChildren,
  LabGovernanceRoute: LabGovernanceRoute,
  LabLoopsRoute: LabLoopsRouteWithChildren,
  LabIndexRoute: LabIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
